config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

class AdminConstraint
  def matches?(request)
    return false unless request.session[:current_admin_id].present?
    admin = Administrator.find_by(id: request.session[:current_admin_id])
    admin.present?
  end
end

Rails.application.routes.draw do

  resources :blogs, only: [:show, :edit] do
    resources :likes, only: [:index, :create, :destroy]
    resources :comments, only: [:index, :create] do
      collection do
        get :refresh
      end
    end
  end

  resources :archives, only: [:index]
  resources :photos, only: [:create]

  get '/about', to: 'home#about'
  get '/changelog', to: 'home#changelog'

  namespace :admin do
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout
    resource :account, only: [:edit, :update]

    resources :posts, only: [:index, :new, :edit, :create, :update, :destroy] do
      collection do
        post :preview
      end
      resources :comments, only: [:index, :destroy]
    end

    resources :all_comments, only: [:index, :destroy]
    resources :labels


    root to: 'dashboard#index'
  end

  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new
  #mount ActionCable.server => '/cable'
  root to: 'home#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :name, presence: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :content, presence: true, length: { minimum: 4 }

  def reply_emails
    Comment.where(post_id: self.post_id).collect(&:email).uniq - [ self.email ] - Subscribe.unsubscribe_list - [ ENV['ADMIN_USER'] ]
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::BaseController
  before_action do
    @post = Post.find( params[:post_id] )
  end

  def index
    @comments = @post.comments.order(created_at: :desc)
  end

  def destroy
    comment = @post.comments.find(params[:id])
    if comment.destroy
      flash[:notice] = '删除评论成功'
      redirect_to admin_post_comments_path(@post)
    else
      flash[:alert] = '删除失败'
      redirect_to admin_post_comments_path(@post)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  layout false

  def create
    cookies[:name] = comment_params[:name]
    cookies[:email] = comment_params[:email]

    @post = Post.find( params[:blog_id] )
    @comments = @post.comments.order(created_at: :desc)

    # # 某些原因暂时关闭评论
    flash.now[:notice] = '评论功能未开放'
    return

    @comment = @post.comments.build(comment_params)
    if @comment.save
      flash.now[:notice] = '发表成功'
      # 重置评论
      @comment = Comment.new
    end
  end

  def refresh
    @post = Post.find(params[:blog_id])
    @comments = @post.comments.order(created_at: :desc)
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :name, :email)
  end
end

app/views/admin/comments/index.html.slim
.card
  .card-header
    .float-sm-left
      h3.card-title
        ' #{t('admin.comments')}
        | / #{@post.title}
  .card-body
    table.table.table-hover
      thead
        tr
          th #{t('admin.comments_head.name')}
          th #{t('admin.comments_head.email')}
          th #{t('admin.comments_head.content')}
          th #{t('admin.comments_head.created_at')}
          th #{t('admin.comments_head.operation')}
      tbody
        - @comments.each do |comment|
          tr
            td #{comment.name}
            td
              = mail_to comment.email
            td
              = simple_format(comment.content)
            td
              = format_time(comment.created_at)

            td
              = link_to t('admin.comments_head.reply'), blog_path(@post, anchor: 'new_comment'), target: '_blank', class: 'edit-post-link'
              '
              = link_to t('admin.comments_head.destroy'), admin_post_comment_path(@post, comment), method: 'DELETE', 'data-confirm'=> '确认删除?'