config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

class AdminConstraint
  def matches?(request)
    return false unless request.session[:current_admin_id].present?
    admin = Administrator.find_by(id: request.session[:current_admin_id])
    admin.present?
  end
end

Rails.application.routes.draw do

  resources :blogs, only: [:show, :edit] do
    resources :likes, only: [:index, :create, :destroy]
    resources :comments, only: [:index, :create] do
      collection do
        get :refresh
      end
    end
  end

  resources :archives, only: [:index]
  resources :photos, only: [:create]

  get '/about', to: 'home#about'
  get '/changelog', to: 'home#changelog'

  namespace :admin do
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout
    resource :account, only: [:edit, :update]

    resources :posts, only: [:index, :new, :edit, :create, :update, :destroy] do
      collection do
        post :preview
      end
      resources :comments, only: [:index, :destroy]
    end

    resources :all_comments, only: [:index, :destroy]
    resources :labels


    root to: 'dashboard#index'
  end

  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new
  #mount ActionCable.server => '/cable'
  root to: 'home#index'
end

app/controllers/blog_controller.rb
# app/controllers/blog_controller.rb

class BlogController < ApplicationController
  before_action :set_post, only: [:show, :create_comment, :update_comment, :destroy_comment]
  before_action :set_comment, only: [:update_comment, :destroy_comment]

  def show
    if comments_enabled?
      @comments = @post.comments
    else
      @comments = []
    end
  end

  def create_comment
    if comments_enabled?
      @comment = @post.comments.build(comment_params)
      if @comment.save
        redirect_to @post, notice: 'Comment was successfully created.'
      else
        render :show
      end
    else
      redirect_to @post, alert: 'Comments are disabled.'
    end
  end

  def update_comment
    if comments_enabled?
      if @comment.update(comment_params)
        redirect_to @post, notice: 'Comment was successfully updated.'
      else
        render :show
      end
    else
      redirect_to @post, alert: 'Comments are disabled.'
    end
  end

  def destroy_comment
    if comments_enabled?
      @comment.destroy
      redirect_to @post, notice: 'Comment was successfully deleted.'
    else
      redirect_to @post, alert: 'Comments are disabled.'
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:author, :content)
  end

  def comments_enabled?
    Rails.application.config_for(:features)['comments_enabled']
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def show
    cookies[:cable_id] = SecureRandom.uuid
    @post = Post.find(params[:id])
    @post.visited
    @prev = Post.where('created_at < ?', @post.created_at).order(created_at: :desc).first
    @next = Post.where('created_at > ?', @post.created_at).order(created_at: :asc).first
    @comments = @post.comments.order(created_at: :desc)
    @likes_count = @post.likes.count
  end

  def edit
    @post = Post.find(params[:id])
    redirect_to edit_admin_post_path(@post)
  end
end

app/views/blogs/_comment.html.slim
turbo-frame#comment-frame
  .container
    .row.justify-content-center
      .col-12.col-lg-9
        - comment = @comment || Comment.new
        = simple_form_for comment, url: blog_comments_path(post), remote: true do |f|
          = f.text_area :content, placeholder: t('comment_placeholder.content')
          .row
            .col-12.col-lg-6
              = f.text_field :name, value: cookies[:name], placeholder: t('comment_placeholder.name')
          .row
            .col-12.col-lg-6
              = f.text_field :email, value: cookies[:email], placeholder: t('comment_placeholder.email')
          button.comment-submit type='submit' data-disable-with=t('comment_placeholder.submitting') #{t('comment_placeholder.submit')}
          - if info = flash.now[:notice]
            #alert-container.alert.alert-success
              span.text #{info}
              // ai fix
              button class="close" type='button' data-dismiss='alert'
                span &times;
          - elsif comment.errors.any?
            #alert-container.alert.alert-warning
              span.text #{comment.errors[:content].first}
              button class="close" type='button' data-dismiss='alert'
                span &times;
        = render partial: 'comments/comment_content', locals: { comments: comments }

app/views/blogs/_post.html.slim
= render partial: 'post_head', locals: { post: post }

.content.markdown
  == post.content_html

p.ptag.published-at
  | #{t('announce_at')}
  span #{format_date(post.created_at)}

= render 'common/copyright'
hr.blog-over
p data-controller='like'
  button.like-button class="#{'liked' if post.liked_by?(cookies[:like])}" type='button' data-url=blog_likes_path(post) data-like-target='button' data-action='click->like#toggle'
    span.count #{@likes_count}
    span Like
  .qrcode-controller data-controller='qrcode'
    .qrcode
      a#qrcode-link href='#' data-action='click->qrcode#greet'
        i.fi-link
        | #{t('qr_code')}
    .social-share data-qrcode-target='wrapper'
      .qrcode-wrapper
        = render partial: "qrcode", locals: { str: blog_url(post) }

app/views/blogs/_post_head.html.slim
/ require: locals: { post : post }
h2.blog-title #{post.title}
p.ptag
  span.fa.fa-list
  span #{post.labels_content}

app/views/blogs/_qrcode.html.slim
.qrcode-image
  #image-tag data-url=str
  p #{t('qrcodetips')}

app/views/blogs/edit.html.slim
h1 Blogs#edit
p Find me in app/views/blogs/edit.html.slim

app/views/blogs/show.html.slim
- content_for(:meta) do
  meta name="description" content=@post.meta_content
  meta name="keywords" content=@post.labels_content

- content_for(:title) do
  | #{@post.title}
/ data-url=refresh_blog_comments_path(@post) data-post_id=@post.id
.container.blog-wrapper
  .row.justify-content-center
    .col-xs-12.col-lg-9
      = render partial: "post", :locals=> { post: @post }
.comment-field
  = render partial: 'comment', locals: { comments: @comments, post: @post }
  p
  .container
    .row.justify-content-center
      .col-xs-12.col-lg-9
        - if @prev
          = link_to blog_path(@prev), class: 'prev' do
            i.fa.fa-arrow-left
            | 上一篇
        - if @next
          = link_to blog_path(@next), class: 'next' do
            | 下一篇
            i.fa.fa-arrow-right