config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

class AdminConstraint
  def matches?(request)
    return false unless request.session[:current_admin_id].present?
    admin = Administrator.find_by(id: request.session[:current_admin_id])
    admin.present?
  end
end

Rails.application.routes.draw do

  resources :blogs, only: [:show, :edit] do
    resources :likes, only: [:index, :create, :destroy]
    resources :comments, only: [:index, :create] do
      collection do
        get :refresh
      end
    end
  end

  resources :archives, only: [:index]
  resources :photos, only: [:create]

  get '/about', to: 'home#about'
  get '/changelog', to: 'home#changelog'

  namespace :admin do
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout
    resource :account, only: [:edit, :update]

    resources :posts, only: [:index, :new, :edit, :create, :update, :destroy] do
      collection do
        post :preview
      end
      resources :comments, only: [:index, :destroy]
    end

    resources :all_comments, only: [:index, :destroy]
    resources :labels


    root to: 'dashboard#index'
  end

  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new
  #mount ActionCable.server => '/cable'
  root to: 'home#index'
end

app/models/label.rb
class Label < ApplicationRecord
  has_and_belongs_to_many :posts
  validates :name, presence: true
end

app/controllers/admin/labels_controller.rb
class Admin::LabelsController < Admin::BaseController
  def index
    @labels = Label.all.page(params[:page])
  end

  def new
    @label = Label.new
  end

  def edit
    @label = Label.find(params[:id])
  end

  def create
    @label = Label.new(label_params)
    if @label.save
      redirect_to admin_labels_path, notice: '创建成功'
    else
      render :new
    end
  end

  def update
    @label = Label.find(params[:id])
    @label.update!(label_params)
    redirect_to admin_labels_path, notice: '更新成功'
  end

  def destroy
    @label = Label.find(params[:id])
    @label.destroy!
    redirect_to admin_labels_path, notice: '删除成功'
  end

  private
  def label_params
    params.require(:label).permit(:name)
  end
end

app/views/admin/labels/_form.html.slim
.row
  .col-sm-6
    = simple_form_for([:admin, @label], html: {novalidate: '' }) do |f|
      = f.input :name
      = f.button :submit

app/views/admin/labels/edit.html.slim
.card
  .card-header
    .float-sm-left
      h3.card-title 修改标签
  .card-body
      = render 'form'

app/views/admin/labels/index.html.slim
.card
  .card-header
    .float-sm-left
      h3.card-title 标签管理
    .float-sm-right
      = link_to '创建标签', new_admin_label_path
  .card-body
    table.table.table-hover
      thead
        tr
          th 标签名
          th 被引用次数
          th 创建时间
          th 操作
      tbody
        - @labels.each do |label|
          tr
            td = label.name
            td = label.posts.count
            td = format_time(label.created_at)
            td
              = link_to '编辑', edit_admin_label_path(label)
              | &nbsp
              = link_to '删除', admin_label_path(label), method: 'DELETE', 'data-confirm' => '确认删除?'
  .card-footer
    .float-sm-left
      | 总计: #{@labels.total_count}
    .float-sm-right
      = paginate @labels

app/views/admin/labels/new.html.slim
.card
  .card-header
    .float-sm-left
      h3.card-title 新建标签
  .card-body
    = render 'form'