config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

class AdminConstraint
  def matches?(request)
    return false unless request.session[:current_admin_id].present?
    admin = Administrator.find_by(id: request.session[:current_admin_id])
    admin.present?
  end
end

Rails.application.routes.draw do

  resources :blogs, only: [:show, :edit] do
    resources :likes, only: [:index, :create, :destroy]
    resources :comments, only: [:index, :create] do
      collection do
        get :refresh
      end
    end
  end

  resources :archives, only: [:index]
  resources :photos, only: [:create]

  get '/about', to: 'home#about'
  get '/changelog', to: 'home#changelog'

  namespace :admin do
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout
    resource :account, only: [:edit, :update]

    resources :posts, only: [:index, :new, :edit, :create, :update, :destroy] do
      collection do
        post :preview
      end
      resources :comments, only: [:index, :destroy]
    end

    resources :all_comments, only: [:index, :destroy]
    resources :labels


    root to: 'dashboard#index'
  end

  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new
  #mount ActionCable.server => '/cable'
  root to: 'home#index'
end

app/views/common/_copyright.en.html.slim
p.copyright.published-at.ptag
  | © Creative Commons - ShareAlike - NonCommercial - Attribution

app/views/common/_copyright.html.slim
p.copyright.published-at.ptag
  | © 自由转载 - 非商用 - 非衍生 - 保持署名

app/views/common/_no_blog_here.en.html.slim
h2.blog-title #{t('home.no_blog_here')}
p
  | No post here, please visit
  = link_to ' Manage Post ', new_admin_post_path
  | to create the first post.

app/views/common/_no_blog_here.html.slim
h2.blog-title #{t('home.no_blog_here')}
p
  | 这里还没有博客, 请访问
  = link_to '管理页面', new_admin_post_path
  | 来创建第一篇博客

app/views/common/_welcome.en.html.slim
/* adjust stylesheet: .self-introduce-index */
h4 WELCOME
p I'm Li Yafei, WinDy is my English name.

h4 ABOUT
ul.aboutme-index
  li
    span Industry:
    span Web Development, Startups, Life
  li
    span Location:
    span Nan Shan District, ShenZhen, China
  li
    span More:
    span
      =  link_to 'About Me', about_path

app/views/common/_welcome.html.slim
/* 样式调整请找 stylesheet: .self-introduce-index */
.box
  h4 欢迎
  p 我是技术达人李亚飞
.box
  h4 关于我
  ul.aboutme-index
    li
      span 领域:
      span 技术, 创业, 生活
    li
      span 位置:
      span 中国 - 北京
    li
      span 更多:
      span
        =  link_to '关于我', about_path

app/views/common/_welcome_new_year.html.slim
- if (1.days.from_now).strftime('%-m-%-d') =~ /^1-[123]$/
  .new-year.alert.alert-success.alert-dismissible.fade.show role='alert'
    strong 🎉 我的朋友，祝你元旦快乐！
    button.close type='button' data-dismiss='alert' aria-label='Close'
      span aria-hidden='true' &times;